"""
React Code Generator module.

Takes a DesignIR (Intermediate Representation) and generates production-ready
React + TypeScript components.

Usage:
    from design2code.generators.react_gen import ReactGenerator
    
    generator = ReactGenerator(ir)
    output = generator.generate(output_dir="./src")
"""

import json
from pathlib import Path
from typing import Optional
from ..ir.model import (
    DesignIR,
    ColorToken,
    TypographyToken,
    ComponentDefinition,
    DesignElement,
    ElementType,
)


class ReactGenerator:
    """Generates React components from a DesignIR."""

    def __init__(self, ir: DesignIR, output_dir: str = "./generated"):
        self.ir = ir
        self.output_dir = Path(output_dir)

    def generate(self) -> dict[str, Path]:
        """
        Generate all React components and theme files.
        
        Returns a dict mapping generated file names to their paths.
        """
        self.output_dir.mkdir(parents=True, exist_ok=True)
        
        generated = {}
        
        # 1. Theme file (design tokens as TypeScript)
        generated["theme.ts"] = self._generate_theme()
        
        # 2. Button component
        generated["Button.tsx"] = self._generate_button()
        
        # 3. Text component
        generated["Text.tsx"] = self._generate_text()
        
        # 4. Navbar component
        generated["Navbar.tsx"] = self._generate_navbar()
        
        # 5. ColorPalette component
        generated["ColorPalette.tsx"] = self._generate_color_palette()
        
        # 6. Index barrel
        generated["index.ts"] = self._generate_index(list(generated.keys()))

        return generated

    def _generate_theme(self) -> Path:
        """Generate theme.ts with all design tokens."""
        colors_code = self._format_colors()
        typography_code = self._format_typography()
        
        code = f"""// Auto-generated by design2code
// DO NOT EDIT MANUALLY - regenerate from source design files

export const colors = {{
{colors_code}}} as const;

export type ColorKeys = keyof typeof colors;

export const typography = {{
{typography_code}}} as const;

export type TypographyKeys = keyof typeof typography;

export const spacing = {{
{self._format_spacing()}}} as const;

export const breakpoints = {{
{self._format_breakpoints()}}} as const;

export const theme = {{
    colors,
    typography,
    spacing,
    breakpoints,
}} as const;

export type Theme = typeof theme;
"""
        path = self.output_dir / "theme.ts"
        path.write_text(code, encoding="utf-8")
        return path

    def _format_colors(self) -> str:
        """Format color tokens as TypeScript object."""
        lines = []
        for color in self.ir.colors:
            key = color.name.upper().replace("-", "_")
            lines.append(f"    {key}: '{color.value}',")
        return "\n".join(lines) + "\n"

    def _format_typography(self) -> str:
        """Format typography tokens as TypeScript object."""
        lines = []
        for typo in self.ir.typography[:15]:  # Limit to top 15
            key = typo.name.replace("-", "_").replace(" ", "_")
            font_family = typo.font_family.replace("-", " ").title()
            lines.append(f"    {key}: {{")
            lines.append(f"        fontFamily: \"'{font_family}', sans-serif\",")
            lines.append(f"        fontSize: '{typo.font_size}px',")
            if typo.font_weight:
                weight = f"\"{typo.font_weight}\"" if typo.font_weight.isalpha() else typo.font_weight
                lines.append(f"        fontWeight: {weight},")
            if typo.letter_spacing:
                lines.append(f"        letterSpacing: '{typo.letter_spacing}',")
            lines.append(f"    }},")
        return "\n".join(lines) + "\n"

    def _format_spacing(self) -> str:
        """Format spacing tokens as TypeScript object."""
        lines = []
        for s in self.ir.spacing:
            lines.append(f"    {s.name}: '{s.value}px',")
        return "\n".join(lines) + "\n"

    def _format_breakpoints(self) -> str:
        """Format breakpoints as TypeScript object."""
        lines = []
        for name, value in self.ir.breakpoints.items():
            lines.append(f"    {name}: {value},")
        return "\n".join(lines) + "\n"

    def _generate_button(self) -> Path:
        """Generate Button.tsx component."""
        primary_color = self._find_color("primary-blue", "#1F41FF")
        secondary_color = self._find_color("accent-purple", "#9747FF")
        text_color = self._find_color("text-secondary", "#575757")
        
        code = """import React from 'react';
import { colors, typography } from './theme';

export interface ButtonProps {
    variant?: 'primary' | 'secondary' | 'dark' | 'light';
    size?: 'sm' | 'md' | 'lg';
    children: React.ReactNode;
    onClick?: () => void;
    className?: string;
    disabled?: boolean;
}

const variantStyles: Record<NonNullable<ButtonProps['variant']>, React.CSSProperties> = {
    primary: {
        backgroundColor: colors.PRIMARY_BLUE,
        color: '#FFFFFF',
    },
    secondary: {
        backgroundColor: colors.ACCENT_PURPLE,
        color: '#FFFFFF',
    },
    dark: {
        backgroundColor: colors.TEXT_SECONDARY,
        color: '#FFFFFF',
    },
    light: {
        backgroundColor: '#FFFFFF',
        color: colors.TEXT_SECONDARY,
        border: '1px solid ' + colors.TEXT_SECONDARY,
    },
};

export const Button: React.FC<ButtonProps> = ({
    variant = 'primary',
    size = 'md',
    children,
    onClick,
    className = '',
    disabled = false,
}) => {
    const baseStyles: React.CSSProperties = {
        fontFamily: typography['button-text']?.fontFamily || "'Encode Sans Expanded', sans-serif",
        fontSize: size === 'sm' ? '11px' : size === 'lg' ? '15px' : '13px',
        letterSpacing: '-0.06em',
        padding: size === 'sm' ? '8px 16px' : size === 'lg' ? '16px 32px' : '12px 24px',
        border: 'none',
        borderRadius: '4px',
        cursor: disabled ? 'not-allowed' : 'pointer',
        opacity: disabled ? 0.5 : 1,
        transition: 'all 0.2s ease-in-out',
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '8px',
    };

    return (
        <button
            className={`btn btn-${variant} btn-${size} ${className}`}
            style={{ ...baseStyles, ...variantStyles[variant] }}
            onClick={onClick}
            disabled={disabled}
        >
            {children}
        </button>
    );
};

export default Button;
"""
        path = self.output_dir / "Button.tsx"
        path.write_text(code, encoding="utf-8")
        return path

    def _generate_text(self) -> Path:
        """Generate Text.tsx component."""
        code = """import React from 'react';
import { colors, typography } from './theme';

export type TextVariant = 
    | 'header1' | 'header2' | 'header3' | 'header4' | 'header5'
    | 'body' | 'body-sm' | 'body-xs'
    | 'link' | 'label' | 'button-text';

export interface TextProps {
    variant?: TextVariant;
    children: React.ReactNode;
    className?: string;
    color?: string;
    as?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'p' | 'span' | 'a' | 'label';
}

const variantMap: Record<TextVariant, React.CSSProperties> = {
    header1: {
        fontFamily: "'Encode Sans Condensed', sans-serif",
        fontSize: '126px',
        fontWeight: 600,
        letterSpacing: '-0.02em',
        lineHeight: 1.1,
        color: colors.BLACK,
    },
    header2: {
        fontFamily: "'Encode Sans Expanded', sans-serif",
        fontSize: '40px',
        letterSpacing: '-0.06em',
        lineHeight: 1.2,
        color: colors.BLACK,
    },
    header3: {
        fontFamily: "'Encode Sans Semi Condensed', sans-serif",
        fontSize: '37px',
        fontWeight: 600,
        letterSpacing: '-0.02em',
        lineHeight: 1.2,
        color: colors.BLACK,
    },
    header4: {
        fontFamily: "'DM Sans', sans-serif",
        fontSize: '24px',
        fontWeight: 'bold',
        letterSpacing: '-0.02em',
        lineHeight: 1.3,
        color: colors.BLACK,
    },
    header5: {
        fontFamily: "'Encode Sans Semi Condensed', sans-serif",
        fontSize: '20px',
        fontWeight: 600,
        letterSpacing: '-0.02em',
        lineHeight: 1.3,
        color: colors.BLACK,
    },
    body: {
        fontFamily: "'Encode Sans Semi Condensed', sans-serif",
        fontSize: '30px',
        letterSpacing: '-0.02em',
        lineHeight: 1.4,
        color: colors.BLACK,
    },
    'body-sm': {
        fontFamily: "'Encode Sans Semi Condensed', sans-serif",
        fontSize: '17px',
        letterSpacing: '-0.02em',
        lineHeight: 1.5,
        color: colors.TEXT_SECONDARY,
    },
    'body-xs': {
        fontFamily: "'Encode Sans Expanded', sans-serif",
        fontSize: '12px',
        letterSpacing: '-0.02em',
        lineHeight: 1.5,
        color: colors.TEXT_SECONDARY,
    },
    link: {
        fontFamily: "'Encode Sans Semi Condensed', sans-serif",
        fontSize: '18px',
        letterSpacing: '-0.02em',
        color: colors.PRIMARY_BLUE,
        textDecoration: 'none',
        cursor: 'pointer',
    },
    label: {
        fontFamily: "'Roboto Flex', sans-serif",
        fontSize: '12px',
        fontWeight: 500,
        letterSpacing: '-0.03em',
        color: colors.TEXT_SECONDARY,
    },
    'button-text': {
        fontFamily: "'Encode Sans Expanded', sans-serif",
        fontSize: '13px',
        letterSpacing: '-0.06em',
        color: colors.BLACK,
    },
};

const defaultElements: Record<TextVariant, string> = {
    header1: 'h1', header2: 'h2', header3: 'h3',
    header4: 'h4', header5: 'h5',
    body: 'p', 'body-sm': 'p', 'body-xs': 'p',
    link: 'a', label: 'span', 'button-text': 'span',
};

export const Text: React.FC<TextProps> = ({
    variant = 'body',
    children,
    className = '',
    color,
    as,
}) => {
    const Component = as || defaultElements[variant];
    
    return (
        <Component
            className={`text text-${variant} ${className}`}
            style={{ ...variantMap[variant], margin: 0, ...(color && { color }) }}
        >
            {children}
        </Component>
    );
};

export default Text;
"""
        path = self.output_dir / "Text.tsx"
        path.write_text(code, encoding="utf-8")
        return path

    def _generate_navbar(self) -> Path:
        """Generate Navbar.tsx component."""
        code = """import React, { useState } from 'react';
import { colors } from './theme';

export interface NavItem {
    label: string;
    href: string;
    active?: boolean;
}

export interface NavbarProps {
    items?: NavItem[];
    logo?: React.ReactNode;
    className?: string;
    breakpoint?: 'desktop' | 'tablet' | 'mobile';
}

const defaultItems: NavItem[] = [
    { label: 'Classes', href: '#classes' },
    { label: 'About us', href: '#about' },
    { label: 'Book with us', href: '#book' },
];

export const Navbar: React.FC<NavbarProps> = ({
    items = defaultItems,
    logo,
    className = '',
    breakpoint = 'desktop',
}) => {
    const [isOpen, setIsOpen] = useState(false);

    return (
        <nav
            className={`navbar navbar-${breakpoint} ${className}`}
            style={{
                width: '100%',
                backgroundColor: colors.WHITE,
                padding: breakpoint === 'mobile' ? '16px' : '24px 40px',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'space-between',
                borderBottom: '1px solid ' + colors.LIGHT_GRAY,
            }}
        >
            <div className="navbar-logo">
                {logo || (
                    <span style={{
                        fontFamily: "'Encode Sans Semi Condensed', sans-serif",
                        fontSize: breakpoint === 'mobile' ? '24px' : '30px',
                        color: colors.BLACK,
                    }}>
                        Movement Studios.
                    </span>
                )}
            </div>

            {breakpoint === 'mobile' ? (
                <>
                    <button
                        onClick={() => setIsOpen(!isOpen)}
                        style={{ background: 'none', border: 'none', cursor: 'pointer' }}
                        aria-label="Toggle menu"
                    >
                        <svg width="24" height="24" viewBox="0 0 24 24" fill="none">
                            <path d="M3 12h18M3 6h18M3 18h18" stroke={colors.TEXT_SECONDARY} strokeWidth="2" strokeLinecap="round"/>
                        </svg>
                    </button>
                    {isOpen && (
                        <div style={{
                            position: 'absolute', top: '100%', left: 0, right: 0,
                            backgroundColor: colors.WHITE, padding: '16px',
                            display: 'flex', flexDirection: 'column', gap: '8px',
                        }}>
                            {items.map(item => (
                                <a key={item.label} href={item.href}
                                   style={{ fontFamily: "'Encode Sans Semi Condensed', sans-serif", fontSize: '18px', color: colors.TEXT_SECONDARY, textDecoration: 'none' }}>
                                    {item.label}
                                </a>
                            ))}
                        </div>
                    )}
                </>
            ) : (
                <div style={{ display: 'flex', gap: '24px', alignItems: 'center' }}>
                    {items.map(item => (
                        <a key={item.label} href={item.href}
                           style={{ fontFamily: "'Encode Sans Semi Condensed', sans-serif", fontSize: '18px', letterSpacing: '-0.02em', color: item.active ? colors.PRIMARY_BLUE : colors.TEXT_SECONDARY, textDecoration: 'none' }}>
                            {item.label}
                        </a>
                    ))}
                </div>
            )}
        </nav>
    );
};

export default Navbar;
"""
        path = self.output_dir / "Navbar.tsx"
        path.write_text(code, encoding="utf-8")
        return path

    def _generate_color_palette(self) -> Path:
        """Generate ColorPalette.tsx component."""
        color_items = ",\n".join([
            f"    {{ name: '{c.name}', value: '{c.value}' }}"
            for c in self.ir.colors
        ])
        
        code = f"""import React from 'react';
import {{ colors }} from './theme';

export interface ColorPaletteProps {{
    className?: string;
    showNames?: boolean;
}}

const colorList = [
{color_items}
];

export const ColorPalette: React.FC<ColorPaletteProps> = ({{
    className = '',
    showNames = true,
}}) => {{
    return (
        <div className={{`color-palette ${{className}}`}} style={{{{
            display: 'flex', flexWrap: 'wrap', gap: '16px', padding: '24px',
        }}}}>
            {{colorList.map((color) => (
                <div key={{color.name}} style={{{{
                    display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '8px',
                }}}}>
                    <div style={{{{
                        width: '64px', height: '64px', backgroundColor: color.value,
                        borderRadius: '8px', border: '1px solid ' + colors.LIGHT_GRAY,
                    }}}} />
                    {{showNames && (
                        <div style={{{{
                            fontFamily: "'Roboto Flex', sans-serif", fontSize: '12px',
                            color: colors.TEXT_SECONDARY, textAlign: 'center',
                        }}}}>
                            <div>{{color.name}}</div>
                            <div>{{color.value}}</div>
                        </div>
                    )}}
                </div>
            ))}}
        </div>
    );
}};

export default ColorPalette;
"""
        path = self.output_dir / "ColorPalette.tsx"
        path.write_text(code, encoding="utf-8")
        return path

    def _generate_index(self, filenames: list[str]) -> Path:
        """Generate index.ts barrel file."""
        component_names = [
            f.split(".")[0] for f in filenames if f.endswith(".tsx")
        ]
        exports = "\n".join([
            f"export {{ {name} }} from './{name}';"
            for name in component_names
        ])
        
        code = f"""// Auto-generated by design2code
// DO NOT EDIT MANUALLY

{exports}
export {{ theme, colors, typography, spacing, breakpoints }} from './theme';
export type {{ Theme, ColorKeys, TypographyKeys }} from './theme';
"""
        path = self.output_dir / "index.ts"
        path.write_text(code, encoding="utf-8")
        return path

    # --- Helper methods ---

    def _find_color(self, semantic_hint: str, fallback: str) -> str:
        """Find a color by semantic name or return fallback."""
        for color in self.ir.colors:
            if semantic_hint.lower() in color.name.lower():
                return color.value
        return fallback
